### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by TattCherr** [oleksandrblazhko/PAI202-Chernishova#1]
«laboratory-work-0».

**Comment by oleksandrblazhko** [comment]
Якщо у вас є складності з роботою із локальним Git-рпозиторієм, тоді всі завдання виконуйте безпосередньо через GitHub.
У завданні 5.1 ЛР0 зазначено наступне: 
"Розпочинаючи роботу над завданнями лабораторної роботи, необхідно створити нову Git-гілку з назвою, яка відповідає назві Issue, наприклад, «laboratory-work-0». "
Створіть таку гілку і вже в цій гілці виконайте завдання 6 зі створення файлу README.md
Якщо будуть питання, пишіть на пошту.

**Comment by TattCherr** [comment]
Я зараз намагаюся розібратися. Пробачте, якщо ми бачите усі мої намагання щось зробити.

**Comment by oleksandrblazhko** [comment]
Не треба вибачень, бо це навчальний процес.
Все добре. 
Бачив, що ви створили гілку для ЛР1. 
Але спочатку треба завершити виконання роботи ЛР0.

**Comment by TattCherr** [comment]
Це правда. Працюємо не для оцінки, а для отримання знань.

**Comment by oleksandrblazhko** [comment]
Алгоритм взаємодії такий:
1) ви створюєте гілку
2) переходите до гілки
3) створюєте файл README.md та редагуєте його
4) виконуєте Pull Request
5) я перевіряю рішення і якщо все гаразд закриваю ваш Pull Request
6) після закриття Pull Request всі ваші зміни з файлом README.md перейдуть до основної гілки main GitHub-репозиторію

Тому ця лабораторная робота має номер 0, бо там мало завдань, пов'язани з темою безпеки, а більше завдань, пов'язаних з темою роботи в GitHub-репозиторії.

**Comment by TattCherr** [comment]
Я зробила першу спробу з pull-request. Якщо не вдалося його зробити, пишіть, буду поступово розбіратися.

**Comment by oleksandrblazhko** [comment]
Pull Request ви зробили. Все гаразд.
Але тепер треба ще раз:
1) зайти до гілки [1-laboratory-work-0]
2) відредагувати файл README.md як це вказано у завданні 6.5

**Comment by TattCherr** [comment]
Спасибі. Йдемо ділі.

**Comment by oleksandrblazhko** [comment]
Але треба запам`ятати, що Pull Request робиться на останньому кроці - після того, як виконано всі завдання і ви готові надати ваші рішення на перегляд та оцінку.
Дякую за активність!

**Comment by oleksandrblazhko** [comment]
Як власник репозиторію і викладач, я бачу лише дві події:
1) створення Issue - яке для мене свідчить, що ви розпочали працівати над завданнями
2) створення Pull Request - яке для мене свідчить, що можна починати перевіряти ваші рішення
