### ISSUE TITLE
«Laboratory Work #7»

### ISSUE THREAD

**Issue by TattCherr** [oleksandrblazhko/PAI202-Chernishova#17]

**Comment by oleksandrblazhko** [comment]
Оцінка = 5 балів

**Comment by TattCherr** [comment]
Пробачте, але тут помилка у 7 лабораторній роботі. Там ще ще немає 1
останньго завдання ( 2.4 Повноважне керування санкціонованим доступом до
даних ) - вже зроблено, хотіла Вам завтра вислати все. Повний pull-request
я ще не робила.

Як ще можна його причепити?

**Comment by oleksandrblazhko** [comment]
Я бачив, що там не вистачає останнього завдання, тому і виставив вам 5
балів, замість 10 балів.
Третє завдання - найскладніше.
Так, можна додати!
Додавайте та відкривайте Pull Request.
Дякую вам за вашу активність у цей складний час!
Ви така у мене перша студентка!

пн, 16 січ. 2023 р. о 02:06 TattCherr ***@***.***> пише:
