### ISSUE TITLE
Laboratory Work #1

### ISSUE THREAD

**Issue by TattCherr** [oleksandrblazhko/PAI202-Chernishova#2]

**Comment by oleksandrblazhko** [comment]
У ришенні ви вказали, що:
Функціональна вимога "FR6. Авторизація, керування паролями" не має загроз порушення конфіденційності та цілісності.
Пароль для вашої системи не є конфіденційним ?

**Comment by TattCherr** [comment]
Здраствуйте,

я думаю, Ви повністю маєте рацію.

Під час процесу авторизації можливі атаки на усі 3 компоненти інформаційної
безпеки:
- конфіденційність, якщо, наприклад, неавторизовані користувачі під час
атаки отримують доступ до системи та її секретних даних, наприклад, як Ви
сказали, паролі
- цілістніть, наприклад, коли несанкційовані особи отримають авторизацію та
право до змін у системи
- доступність, наприклад, коли зруйновано доступ для авторизованих
користувачів.

Згодна з Вами.

Тетяна

**Comment by oleksandrblazhko** [comment]
Отлично!
Оценка = 5 баллов!

**Comment by oleksandrblazhko** [comment]
Создайте Pull Request для этой работы, чтобы я мог ее закрыть.
